language: node_js
sudo: required
install:
#- gem uninstall heroku
- npm install
- jspm install
before_install:
#- sudo wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: s9a6U+M6SHl1RCMpjvumYNXVdD38orpSlQeBOCrZwG4MG+zrp8Zw77A+ZutrGWvsqugOh6kH0OpTusi0s+drqSOo8WIC5nRbFpTV8IefTwjamS0cuX7MdxE9W4M+3m0XGvAkT8XjsNdbdtDjyDje8botJ3q0NAzG1NQBHDeHyd/IwK2cwIW4WFJHZw8ywLbbj/9vD12Ku0LQYTR/HKtdOVFiH6mBJJ4tv4UoCp0s+bdij6OGxV7h/vJwptSuwusyR583G2TI858S35mbqwtFgNcPW8Bu0h5CVZRzSG9hmV2QdWYJWfhI9+OhI5sXYav9hBYRyc8AzxZZsXQh80mGrcc4HlzwKDH7o1n9+6P4dZc6EAJarXpQTzvSxTK+cB6KHq1mh1hNBUw5sGfts6kXN9A+XNTAQ3GR6WMciByw/2XIBLAW/qFBHv+SWaMKKvkEcWibhXoEfpwezY4nrE1Q8FuXsmuMIJsECrsXrTaYoTM1AITMpJ+pOX3GYaRfQ/6wmUMpwZhvwdPv9MOx6BxMGNOIph6m7Xri5ZvOXbRtFqxiPjMLl7KsmRr0/Q29svKoqm1XRIsdzjS/5bsiz7PVHCuOPpjbQkpZ3oSSH5byMWLctWVHu4Lk6mnpBzNuPNImT8jGRG8QqpJgsjh9tKWGhhprCcDdDiOaATr/aF/dtic=
