language: node_js
node_js:
  - "0.12"
install:
- npm install
- jspm install
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: kXEWcaEDLOHSQMIPRr7O7M5CiNucXpv09nKGQsoc3SROsgTVdCz2miZUT5rpYRB8FNCxUC3zRSW8oA3aEVKkB9ljqIV13gLt2nCTcT2rfyIILaVIFShYJkfkKx1Rq9t+osWflFv978AEGR68YUE3fUiMxRzj9KBWEe7nRIOP9aPBY/CbPq1IRhFhqgMGOI5C+tvnG3oAB+nktzxRp6mlFbrIAFAei7O+2iqrkSqh6+Z7OPOqS/FgCCEsnKj8brMwJ/k8B//+MTu82ikRtc3+UvWcp2Y0JnSEXc7SSVNIDByb1kcrc5Py9zmvTLHofjCL9Dj3t1qZ1EFB+t0xGWjFLSlnZnMKbjeeR5EN9NlxpSj3rJE33Qg1Klcm386eqDPQUB6xOJaoWK1R94PHkSjAbG73d3dbqJB9Kgxd5BQetp38AVlHD8MJi5tH8t/ji+/itp7ihMxHtllfSuFYkZ4o6VAFzWJFSQi0fRFbT+TVCa2F4xv76VFQLtOudLOBeOAdJ61KzVj3fRSrKFO3kObq9P/5H0a/xNsuy7j0u02DSFbegibE8zABbsqJuCW9LS7yeqSt1LhzV/ffNbvoHgOMkKIUaz7+A/rIyejjpeWAly6lTEox7yjqjFqZhDY1a9+i4w9W/4fydJKcdzVOkU0O30KHyetFVHg2KcmFZdfDAgI=
  app: blaze-ulc
  on:
    repo: marthinus-engelbrecht/blaze_ulc
after_deploy:
  - npm test:functional
  - heroku pipelines:promote blaze-ulc-development
env:
  global:
    - secure: BtpNNJWubC3g3lDrZQYIJbOo8ZYq1AdSteI3ZpoCXsOnodzrzzNc1L3FEhc4oR03DcVnWS0KTD3WslgMjE8bHezUQNugxNS01H4YrE7DlImI09sa3yMZ+JFvwZ1G+NI6tP7bqbYMb1nPDWPkHHsopTR2Qiul0PezEtxDt59/2/njUna++4wpdUwI2XuGM/BCwvNOdqtrWxl9MOEvXi5NaDSwAwRcQ7CLZcpjlVaXJE2uOpkSG4GDRuFGYJVCAqa+Y05RXhpfkIh0c0d6SrXJ64Wh/wQLWWzgc6fJM6+dEcWuNAeGfG/PJNMM8u7Pvm9hp7kaQcdIvQ4beooIpY1LhTeN1VxLB/pyq95vDRpC9XSYmuU+d7rqbwNR+vvDCyNFkWnDBcaJ2gVsn5FZMG0y71m0UBYy6M3S8P8mblnAE6ydUmPQImd59LQkCSonWl85SmdUrGLl5vVtI1/fUnFkoFG8qvQCydvgx2qi6/CWg/iicijqKZnWNyTS0W2w/oP/hAb1Zgw/O1FUbvTPJGWX6rt+cnKfKVBofqdg0U0XpcDkVorD9y6rK7iGYJ8Gxmf7UJ4yDfjHKsATl8UuEY84abCp6CPDuZKwA0bL4FB94QQcWNNzPbgC8y+OwbHYVEpF+IM7oSugz9YaSLwHKcGNiz8JM1Jz/+N8OvVIUYn2Swk=
    - secure: P7s5abwc8BZqYowaS9GR+qAV06kVESKlOVkWOpX7MxqYdXeoWp+SJlWflHqG3ies21I5vT+/RNUaA/YAoPjGSv6RUJVOIpGkeOAgVK5lA1Cdv5xpwvCHd62PVd2eSuVmUcdQ1Tcvqno3A2FSRJDeNbUedMp1nuW/Yf/oeDMepSL+hw1hPBz8IMZM/hDBV3ZiGe+yGTKPy4fLGYt56ApEoCJxWfTgPirFGuaXNL+KFmPRuieRH1doA1Tq0sQ5C8YeA5oT4/4AnhGXneKZ1AFog90ziXa8p8xQC2oFldJqFrIyvmj72qvkyiYqzdYCYcCP/akyQvLUXXKiuiWIXW2kDWSIjighWKPZFnfEVRAkf71JFWeBwdRjV9gJIm3/Sc5XuGeoBgVb9WN0Hwo/XCic1qOwo94ZSBauMWZt0Qx7sFjwA6yNgL1PlxRWltjS+uWawmbG63wGMJjkQPfVW90yijChFP+ZSOz1EYh2/sZFt2wbW7teDT/69pJcY+TWcvlFGmXVK0d1D/uUxbvHVEzyNXlxwWbVtPgy1R7B8Z3ruG3inmp4a7+8joMgzZI81z4/SrEw0Rz3CE2P83Pm8rf7S0Lv7vuzKPj33dTMm1eo2cFlhBxW2GnJtxlvBCkKJXU6Zg0+Z1tsawNTxmMdEeeksDcfuCOptj/VgJqqtiCVaQk=
    - secure: Mm5Un806ND37vmKpJ7oIc+PWoFcDLpk51LsYnjhlfTVo5jrUKbTKOIrF6Dxk7MtYUvcp6SySts3FWSsvmv+HefUDZMvX0JYInwQ8/vG/jMc86ii8JbdpjgH9m0NAc3fG3fh/qHCCTKLHkHLI9+QvD1h+uzNd8xOMEXS5drlg3j122yaWeGhbtd2JaMTwoEv7TNkLrwBaaeCFP7k95VEU5IbvYpBEDxLWf4mf1KgLiSF4r97melDrvfLeunRkE01gEw+Qvy+yduvcjZmp/rQR1lb4306qhMrlZBqURsyVTSb780IGAYWPsfKdmBCIHeQRwltFYZCSHIMkzsJcd6hym3HtHTMsL0zxv6JQbBJsQKM1sHcsnOUrq6SUSnD4rHzutaxkOS5ihbzKsd5AK6+kxdwgrAJ2K706SX4Nl9cp6dw/6tPkFLyGKvG5+GWlLMOMY0jA0+suaXVLLhvtCqzZP/NPLNNUUKUMRutWw+Jd4t4rdf3MmbWr1GdoYx93nNzMQgqv3Mwd5kJqChCE0MXN8qui+oZURUkXAX+UVT/goLpuMtwTS4TNVa9c8yJXXRphjrO/r8+HaFPUNGBpdAfzrK7PoRPXITEXTI+t0GmL9RP2IO9bytlU/wqEgGSphJrvM6RlV+Z09RK04/DqpLrVZrvkpRk8wcW1JrP8dosr5n0=

