language: node_js
install:
- npm install
- jspm install
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: kXEWcaEDLOHSQMIPRr7O7M5CiNucXpv09nKGQsoc3SROsgTVdCz2miZUT5rpYRB8FNCxUC3zRSW8oA3aEVKkB9ljqIV13gLt2nCTcT2rfyIILaVIFShYJkfkKx1Rq9t+osWflFv978AEGR68YUE3fUiMxRzj9KBWEe7nRIOP9aPBY/CbPq1IRhFhqgMGOI5C+tvnG3oAB+nktzxRp6mlFbrIAFAei7O+2iqrkSqh6+Z7OPOqS/FgCCEsnKj8brMwJ/k8B//+MTu82ikRtc3+UvWcp2Y0JnSEXc7SSVNIDByb1kcrc5Py9zmvTLHofjCL9Dj3t1qZ1EFB+t0xGWjFLSlnZnMKbjeeR5EN9NlxpSj3rJE33Qg1Klcm386eqDPQUB6xOJaoWK1R94PHkSjAbG73d3dbqJB9Kgxd5BQetp38AVlHD8MJi5tH8t/ji+/itp7ihMxHtllfSuFYkZ4o6VAFzWJFSQi0fRFbT+TVCa2F4xv76VFQLtOudLOBeOAdJ61KzVj3fRSrKFO3kObq9P/5H0a/xNsuy7j0u02DSFbegibE8zABbsqJuCW9LS7yeqSt1LhzV/ffNbvoHgOMkKIUaz7+A/rIyejjpeWAly6lTEox7yjqjFqZhDY1a9+i4w9W/4fydJKcdzVOkU0O30KHyetFVHg2KcmFZdfDAgI=
  app: blaze-ulc
  on:
    repo: marthinus-engelbrecht/blaze_ulc
  strategy: git-ssh
env:
  global:
    secure: Coahv9NOFjMKwlq8OgzsuleCmhsiuvr/cgrSVX8Wicq8lLxvIaQ4wraHS4M3Mwn5AddqOKj/I97acx/moATzUde3Ys7s4Tv1MNGXyF+lROccKWLlsz934Lm7txQuD4O8m71Bviy20cYeUCLKGr3AFO02ZpeQZHSH5S+apBZ7mwZk81IC7qLLqygKEZutODz7/b7OspsU7k7ihrAKVcF0XnvQMFMYH+3bkXOf2oEXQAmaUjWm41PumzCXz0FoeKsyg/dtnf9EN9hCIK6lVA+WMQyiqADN+Ck37vxBGAyH0xvoEiV0mWrxspSx/ISdfYBU8ES8A0CDShqA1lz7xJV9UKFEBi+Slto9HstVIQSQWZKXqvdB/jXsS3Gh1ezSk2zzmTztCgHPru1wG5q6RZ7kLGRe/xv1JLRseI96dPKI1ieaAUpklsKsMWoJX1sWrVrPSDK/wORjig+/4Oj4GBqZs/UTQOiQ4Iekg0CEQGCudtUKSApy/vCH2Re34GvWVMZNO8qi1MzTks/MUc2sfaNlnBz1ncqgIp5Sd/HaJqi73He72IqlFXVwSEg2T0jqtwFGlB7NdChWBHYEWb23t2xKdiUtkzXHzrQ6oQdXtgAcMAllTEdkrD8VdX9AKd9Oq6J/wEdff2DKu534lgnRQPhJjwnhpxe9KTOiZCKzh1DZLT8=
